export const locales: Record<string, string> = {
  af_za: "Afrikaans (Suid-Afrika)",
  ar_sa: "العربية (العالم العربي)",
  ast_es: "Asturianu (España)",
  az_az: "Azərbaycanca (Azərbaycan)",
  ba_ru: "Башҡортса (Рәсәй)",
  bar: "Boarisch",
  be_by: "Беларуская (Беларусь)",
  be_latn: "Biełaruskaja (Łacinka)",
  bg_bg: "Български (България)",
  br_fr: "Brezhoneg (Frañs)",
  brb: "Braobans",
  bs_ba: "Bosanski (Bosna i Hercegovina)",
  ca_es: "Català (Espanya)",
  cs_cz: "Čeština (Česko)",
  cv_cu: "Чӑвашла",
  cy_gb: "Cymraeg (Y Deyrnas Unedig)",
  da_dk: "Dansk (Danmark)",
  de_at: "Deutsch (Österreich)",
  de_ch: "Deutsch (Schweiz)",
  de_de: "Deutsch (Deutschland)",
  el_gr: "Ελληνικά (Ελλάδα)",
  en_au: "English (Australia)",
  en_ca: "English (Canada)",
  en_gb: "English (United Kingdom)",
  en_nz: "English (New Zealand)",
  en_pt: "English (Pirate)",
  en_ud: "English (Upside Down)",
  en_us: "English (United States)",
  enp: "Anglish",
  enws: "English (Shakespearean)",
  eo_uy: "Esperanto (Urugvajo)",
  es_ar: "Español (Argentina)",
  es_cl: "Español (Chile)",
  es_ec: "Español (Ecuador)",
  es_es: "Español (España)",
  es_mx: "Español (México)",
  es_uy: "Español (Uruguay)",
  es_ve: "Español (Venezuela)",
  esan: "Español Andaluz",
  et_ee: "Eesti (Eesti)",
  eu_es: "Euskara (Euskal Herria)",
  fa_ir: "فارسی (ایران)",
  fi_fi: "Suomi (Suomi)",
  fil_ph: "Filipino (Pilipinas)",
  fo_fo: "Føroyskt (Føroyar)",
  fr_ca: "Français (Canada)",
  fr_ch: "Français (Suisse)",
  fr_fr: "Français (France)",
  fra_de: "Fränggisch",
  fur_it: "Furlan (Italia)",
  fy_nl: "Frysk (Nederlân)",
  ga_ie: "Gaeilge (Éire)",
  gd_gb: "Gàidhlig (Alba)",
  gl_es: "Galego (España)",
  go_fr: "Gallo (France)",
  hal_ua: "Гальська",
  haw_us: "ʻŌlelo Hawaiʻi (ʻAmelika)",
  he_il: "עברית (ישראל)",
  hi_in: "हिन्दी (भारत)",
  hn_no: "Høgnorsk",
  hr_hr: "Hrvatski (Hrvatska)",
  hu_hu: "Magyar (Magyarország)",
  hy_am: "Հայերեն (Հայաստան)",
  id_id: "Bahasa Indonesia (Indonesia)",
  ig_ng: "Igbo (Naịjịrịa)",
  io_en: "Ido",
  is_is: "Íslenska (Ísland)",
  isv: "Medžuslovjansky",
  it_it: "Italiano (Italia)",
  ja_jp: "日本語 (日本)",
  jbo_en: "la .lojban.",
  ka_ge: "ქართული (საქართველო)",
  kk_kz: "Қазақша (Қазақстан)",
  kn_in: "ಕನ್ನಡ (ಭಾರತ)",
  ko_kr: "한국어 (대한민국)",
  ksh: "Kölsch",
  kw_gb: "Kernewek (Pennow)",
  ky_kg: "Кыргызча (Кыргызстан)",
  la_la: "Latina",
  lb_lu: "Lëtzebuergesch (Lëtzebuerg)",
  li_li: "Limburgs",
  lmo: "Lombard",
  lo_la: "ລາວ (ລາວ)",
  lol_us: "LOLCAT",
  lt_lt: "Lietuvių (Lietuva)",
  lv_lv: "Latviešu (Latvija)",
  lzh: "文言",
  mk_mk: "Македонски (Македонија)",
  mn_mn: "Монгол (Монгол)",
  ms_my: "Bahasa Melayu (Malaysia)",
  mt_mt: "Malti (Malta)",
  nah: "Nāhuatl",
  nds_de: "Plattdüütsch",
  nl_be: "Nederlands (België)",
  nl_nl: "Nederlands (Nederland)",
  nn_no: "Norsk Nynorsk (Noreg)",
  no_no: "Norsk Bokmål (Norge)",
  oc_fr: "Occitan (França)",
  ovd: "Övdalsk",
  pl_pl: "Polski (Polska)",
  pls: "Polszczyzna",
  pt_br: "Português (Brasil)",
  pt_pt: "Português (Portugal)",
  qcb_es: "Quenya",
  qid: "Quenya (Sindarin)",
  qya_aa: "Quenya",
  ro_ro: "Română (România)",
  rpr: "Русиньскый",
  ru_ru: "Русский (Россия)",
  ry_ua: "Русиньскый (Україна)",
  sah_sah: "Саха тыла",
  se_no: "Davvisámegiella",
  sk_sk: "Slovenčina (Slovensko)",
  sl_si: "Slovenščina (Slovenija)",
  so_so: "Soomaali (Soomaaliya)",
  sq_al: "Shqip (Shqipëri)",
  sr_cs: "Српски (Ћирилица)",
  sr_sp: "Srpski (Latinica)",
  sv_se: "Svenska (Sverige)",
  sxu: "Säggs'sch",
  szl: "Ślōnskŏ gŏdka",
  ta_in: "தமிழ் (இந்தியா)",
  th_th: "ไทย (ประเทศไทย)",
  tl_ph: "Tagalog (Pilipinas)",
  tlh_aa: "tlhIngan Hol",
  tok: "toki pona",
  tr_tr: "Türkçe (Türkiye)",
  tt_ru: "Татарча (Россия)",
  tzo_mx: "Tsotsil",
  uk_ua: "Українська (Україна)",
  uz_uz: "Oʻzbekcha (Oʻzbekiston)",
  val_es: "Valencià (Espanya)",
  vec_it: "Vèneto (Italia)",
  vi_vn: "Tiếng Việt (Việt Nam)",
  vp_vl: "Väpür",
  vro: "Võro",
  yi_de: "ייִדיש",
  yo_ng: "Yorùbá (Nàìjíríà)",
  zh_cn: "简体中文（中国）",
  zh_hk: "繁體中文（香港）",
  zh_tw: "繁體中文（台灣）",
  zlm_arab: "بهاس ملايو (جاوي)",
};
